language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "6"
node_js:
    - "4"
    - "6"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
        - NAME=agenda
        - TOKEN=apptoken
before_install:
    - npm install forever coffee-script -g
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install # data-system
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - sleep 5
    - coffee commands.coffee test-install agenda
    - cd ..
script:
    - npm run build
    - npm run test
